{"target_node": "DynamoDB_AWS::DynamoDB", "root_cause_node": "lambda_step_readDDB_AWS::Lambda", "issue_type": "latency", "severity": 0.03299873412305555, "affected_column": "latency_p90", "timestamp": "2024-05-30 04:28:52.396246", "paths": ["AWS::StepFunctions::StateMachine", "lambda_step_readDDB_AWS::Lambda", "lambda_step_readDDB_AWS::Lambda::Function", "lambda_step_readDDB", "DynamoDB_AWS::DynamoDB"]}